#!/usr/bin/env python

import sys
from game.models import *
from admin.web import run_admin


if len(sys.argv) == 1:
    print("invalid usage")
    exit(1)

if sys.argv[1] == "createdb":
    create_db()
elif sys.argv[1] == "createworld":
    create_world()
elif sys.argv[1] == "createherostates":
    create_hero_actions()
elif sys.argv[1] == "admin":
    run_admin()
